name: edgex-influx-proxy
adopt-info: edgex-influx-proxy
title: EdgeX Foundry InfluxDB Proxy Server
license: GPL-3.0
summary: Proxy data from EdgeX device services to InfluxDB using export-distro
base: core18
description: |
  The EdgeX InfluxDB Proxy server uses the Application Functions Go SDK to 
  recieve events via the message bus and insert all Readings into an InfluxDB
  database.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: i386
  - build-on: armhf

apps:
  influxproxy:
    command: bin/edgex-influx-proxy -confdir $SNAP_DATA/config/edgex-influx-proxy -profile res --registry $CONSUL_ADDR
    daemon: simple
    environment:
      CONSUL_ADDR: "consul://localhost:8500"
    restart-condition: always
    plugs:
      - network-bind
      - network

parts:
  edgex-influx-proxy:
    source: .
    plugin: make
    build-snaps:
      - go
    build-packages: [mercurial, git, build-essential, pkg-config]
    stage-packages: [libzmq3-dev]
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cd $SNAPCRAFT_PART_SRC
      make build

      install -DT "./cmd/edgex-influx-proxy" "$SNAPCRAFT_PART_INSTALL/bin/edgex-influx-proxy"
      install -d "$SNAPCRAFT_PART_INSTALL/config/edgex-influx-proxy/res/"

      # Override LogFile and ProfilesDir
      cat "./cmd/res/configuration.toml" | \
        sed -e s:\"./edgex-influx-proxy.log\":\'\$SNAP_COMMON/edgex-influx-proxy.log\': \
        -e s:'ProfilesDir = \"./res\"':'ProfilesDir = \"\$SNAP_DATA/config/edgex-influx-proxy/res\"': > \
        "$SNAPCRAFT_PART_INSTALL/config/edgex-influx-proxy/res/configuration.toml"

      # install license and attribution.txt
      # TODO: add attribution.txt to this repo
      # install -DT "./cmd/Attribution.txt" \
      #    "$SNAPCRAFT_PART_INSTALL/usr/share/doc/edgex-influx-proxy/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/edgex-influx-proxy/LICENSE"

      snapcraftctl set-version $(cat VERSION)-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
