name: Snap
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-snap:
    name: Snap building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
      - name: Build the snap
        uses: snapcore/action-build@v1
      - name: Uploading snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap-files
          path: "*.snap"
  test-snap:
    runs-on: ubuntu-latest
    needs: build-snap
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
      - name: Download built snap
        uses: actions/download-artifact@v2
        with:
          name: snap-files
      - name: Test built snap
        shell: bash
        run: |
          ./test.sh edgex-influx-proxy*.snap
